export const INITIAL_PROFILES = [
  {
    id: 'cand-001',
    full_name: 'Ananya Deshmukh',
    age: 26,
    gender: 'female',
    city: 'Pune',
    state: 'Maharashtra',
    occupation: 'Senior Software Engineer',
    education_level: 'B.Tech Computer Science',
    height_cm: 165,
    annual_income_lpa: 14.5,
    diet: 'veg',
    marital_status: 'never_married',
    family_type: 'nuclear',
    caste: 'Maratha',
    sub_caste: 'Deshmukh',
    bio: 'Software engineer living in Pune. Looking for a well-educated partner.',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    is_id_verified: true,
    is_fully_verified: true,
    is_profession_verified: true,
    managed_by: 'Self'
  },
  {
    id: 'cand-002',
    full_name: 'Rohan Kulkarni',
    age: 28,
    gender: 'male',
    city: 'Mumbai',
    state: 'Maharashtra',
    occupation: 'Financial Analyst',
    education_level: 'MBA Finance',
    height_cm: 178,
    annual_income_lpa: 18.0,
    diet: 'veg',
    marital_status: 'never_married',
    family_type: 'nuclear',
    caste: 'Brahmin',
    sub_caste: 'Deshastha',
    bio: 'Finance professional working in South Mumbai.',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    is_id_verified: true,
    is_fully_verified: true,
    is_profession_verified: true,
    managed_by: 'Self'
  },
  {
    id: 'cand-003',
    full_name: 'Pooja Sharma',
    age: 27,
    gender: 'female',
    city: 'Delhi NCR',
    state: 'Delhi',
    occupation: 'Resident Doctor',
    education_level: 'MBBS, MD',
    height_cm: 160,
    annual_income_lpa: 16.0,
    diet: 'non-veg',
    marital_status: 'never_married',
    family_type: 'joint',
    caste: 'Brahmin',
    sub_caste: 'Gaur',
    bio: 'Doctor practicing in AIIMS Delhi.',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    is_id_verified: true,
    is_fully_verified: false,
    is_profession_verified: true,
    managed_by: 'Parent'
  },
  {
    id: 'cand-004',
    full_name: 'Aditya Joshi',
    age: 29,
    gender: 'male',
    city: 'Bengaluru',
    state: 'Karnataka',
    occupation: 'Architect & Interior Designer',
    education_level: 'B.Arch',
    height_cm: 175,
    annual_income_lpa: 12.0,
    diet: 'veg',
    marital_status: 'never_married',
    family_type: 'nuclear',
    caste: 'Brahmin',
    sub_caste: 'Chitpavan',
    bio: 'Founder of a studio in Bengaluru.',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    is_id_verified: true,
    is_fully_verified: false,
    is_profession_verified: false,
    managed_by: 'Self'
  },
  {
    id: 'cand-005',
    full_name: 'Vikram Patel',
    age: 30,
    gender: 'male',
    city: 'Ahmedabad',
    state: 'Gujarat',
    occupation: 'Operations Manager',
    education_level: 'M.Tech Supply Chain',
    height_cm: 180,
    annual_income_lpa: 15.0,
    diet: 'veg',
    marital_status: 'never_married',
    family_type: 'joint',
    caste: 'Patel',
    sub_caste: 'Kadva',
    bio: 'Operations manager in pharmaceutical firm.',
    photo_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
    is_id_verified: true,
    is_fully_verified: true,
    is_profession_verified: true,
    managed_by: 'Self'
  }
];

export const INITIAL_INTERESTS = [
  {
    id: 'int-001',
    sender_id: 'cand-002',
    receiver_id: 'demo-user-me',
    status: 'pending',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString()
  }
];

export const INITIAL_VERIFICATION_REQUESTS = [];

export default INITIAL_PROFILES;
